### ISSUE TITLE
which cef version used

### ISSUE THREAD

**Issue by mensong** [SriramSakthivel/CefGlueHeadless#1]
Debug it then case a error:

![image](https://github.com/SriramSakthivel/CefGlueHeadless/assets/6715336/527abd8d-946d-4c37-9515-243d9c2045e8)

please help me. 3Q

**Comment by SriramSakthivel** [comment]
You are trying the headless one? This is the binaries you should be using https://cef-builds.spotifycdn.com/index.html#windows64:118.1.1%2Bgd6ce292%2Bchromium-118.0.5993.32 
I have tried in linux, it did not work though, could not find out why yet, in windows it does work.

**Comment by mensong** [comment]
thanks
